version: 0.2
phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - printenv
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - npm run preparepackage
      - >
        aws cloudformation package \
          --template-file ./packaged/template.yml \
          --s3-bucket voip-ms-monitor-build-artifacts \
          --s3-prefix $CODEBUILD_RESOLVED_SOURCE_VERSION
          --output-template-file ./packaged/packaged-tempate.yml
      - aws s3 cp ./packaged/packaged-tempate.yml voip-ms-monitor-build-artifacts/$CODEBUILD_RESOLVED_SOURCE_VERSION/packaged-template.yml