AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  PollVoipMSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: built/index.handler
      Runtime: nodejs6.10
      CodeUri: ./