AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Parameters:
  VoipMSUser:
    Type: String
    Default: ""
  VoipMSPassword:
    Type: String
    Default: ""
  VoipMSAccount:
    Type: String
    Default: ""
  NotificationEmail:
    Type: String
Resources:
  PollVoipMSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: built/index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Environment:
        Variables:
          USER:
            Ref: VoipMSUser
          PASSWORD:
            Ref: VoipMSPassword
          ACCOUNT:
            Ref: VoipMSAccount
          # Tell the Lambda function which table to use:
          ACCOUNT_REGISTRATION_STATUS_TABLE_NAME:
            Ref: AccountRegistrationStatus
          REGISTRATION_STATUS_CHANGE_TOPIC:
            Ref: RegistrationStatusChangeTopic
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: "2012-10-17"
          Statement:
            # Allow the Lambda function to use the table:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource:
                Fn::Sub: arn:aws:dynamodb:::table/${AccountRegistrationStatus}
            # Allow the Lambda function to pubish to the SNS topic:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource:
                Ref: RegistrationStatusChangeTopic
  AccountRegistrationStatus:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: account
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  RegistrationStatusChangeTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Protocol: email
        Endpoint:
          Ref: NotificationEmail