AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Parameters:
  VoipMSUser:
    Type: String
    Default: ""
  VoipMSPassword:
    Type: String
    Default: ""
  VoipMSAccount:
    Type: String
    Default: ""
Resources:
  PollVoipMSFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: built/index.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Environment:
        Variables:
          USER:
            Ref: VoipMSUser
          PASSWORD:
            Ref: VoipMSPassword
          ACCOUNT:
            Ref: VoipMSAccount