AWSTemplateFormatVersion : "2010-09-09"
Description: An experimental test harness for voipms-monitor
Resources:
  # Nested stacks cannot contain Transforms!  Can't use Serverless Application Model for nested stacks :-(
  BadPasswordStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        IntervalMinutes: 2
        NotificationEmail: ""
        VoipMSAccount: "test"
        VoipMSPassword: "test"
        VoipMSUser: "test"
      Tags:
        - Key: Test
          Value: "Bad Password"
      TemplateURL: sqsredirectedtemplate.yml