AWSTemplateFormatVersion : "2010-09-09"
Description: A CloudFormation custom resource that runs a test

Parameters:
  TestParameters: # Should these be passed in to the Lambda or to the Custom::Test?
    Type: CommaDelimitedList
  CodeS3Key:
    Type: String
  LambdaHandler:
    Type: String
  LambdaManagedPolicyArns:
    Type: CommaDelimitedList

Resources:
  TestRunnerLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
      - PolicyName: NoCreateLogGroups
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          # Don't allow Lambda function to re-create its groups while CloudFormation is
          # deleting the stack
          - Effect: Deny
            Action:
            - logs:CreateLogGroup
            Resource: arn:aws:logs:*:*:*
      - PolicyName: InvokeTestFunction
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: "*" # TODO: Limit to specific function(s)?
  CfnTestRunnerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: fillinlater
        S3Key: 
          Ref: CodeS3Key
      Handler:
        built/testLambda.handler
      Runtime: nodejs6.10
      Role:
        Fn::GetAtt: [TestRunnerLambdaExecutionRole, Arn]
      Timeout: 300
  # Create a log group for the Lambda function so that it gets deleted when the stack is deleted.
  CfnTestRunnerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${CfnTestRunnerFunction}
  TestFunctionLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        Ref: LambdaManagedPolicyArns
      Policies:
      - PolicyName: NoCreateLogGroups
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          # Don't allow Lambda function to re-create its groups while CloudFormation is
          # deleting the stack
          # ** Possibly not necessary for this function **
          - Effect: Deny
            Action:
            - logs:CreateLogGroup
            Resource: arn:aws:logs:*:*:*
  TestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: fillinlater
        S3Key: 
          Ref: CodeS3Key
      Handler:
        Ref: LambdaHandler
      Runtime: nodejs6.10
      Role:
        Fn::GetAtt: [TestFunctionLambdaExecutionRole, Arn]
      Timeout: 300
  TestFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${TestFunction}
  Test:
    Type: Custom::Test
    Properties:
      ServiceToken:
        Fn::GetAtt: [CfnTestRunnerFunction, Arn]
      Parameters:
        - Fn::Join:
          - ","
          - Ref: TestParameters
      Function:
        Ref: TestFunction
    DependsOn:
    - TestRunnerLambdaExecutionRole
    - CfnTestRunnerFunctionLogGroup
    - TestFunction
    - TestFunctionLogGroup
Outputs:
  TestResult:
    Value:
      Fn::GetAtt: [Test, Result]
#   CfnTestRunnerFunctionArn:
#     Value:
#       Fn::GetAtt: [CfnTestRunnerFunction, Arn]