AWSTemplateFormatVersion : "2010-09-09"
Description: A CloudFormation custom resource for a GitHub status

Parameters:
  StackTemplateBucketName:
    Type: String
  StackTemplateBucketKeyPrefix:
    Type: String

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
      - PolicyName: NoCreateLogGroups
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          # Don't allow Lambda function to re-create its groups while CloudFormation is
          # deleting the stack
          - Effect: Deny
            Action:
            - logs:CreateLogGroup
            Resource: arn:aws:logs:*:*:*
  GitHubStatusFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: StackTemplateBucketName
        S3Key:
          Fn::Sub: ${StackTemplateBucketKeyPrefix}/PollVoipMSFunction.zip # TODO: Separate?
      Handler: built/githubStatusLambda.handler
      Runtime: nodejs6.10
      Role:
        Fn::GetAtt: [LambdaExecutionRole, Arn]
  # Create a log group for the Lambda function so that it gets deleted when the stack is deleted.
  GitHubStatusFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${GitHubStatusFunction}
Outputs:
  GitHubStatusFunctionArn:
    Value:
      Fn::GetAtt: [GitHubStatusFunction, Arn]