AWSTemplateFormatVersion : "2010-09-09"
Description: This stack wraps the voip-ms template and redirects SNS messages into an SQS queue.
Parameters:
  VoipMSUser:
    Type: String
    Default: ""
  VoipMSPassword:
    Type: String
    Default: ""
    NoEcho: true
  VoipMSAccount:
    Type: String
    Default: ""
  NotificationEmail:
    Type: String
  IntervalMinutes:
    Type: Number
    Default: 5
    MinValue: 2 # 1 doesn't work with Schedule expression as is
Resources:
  # Nested stacks cannot contain Transforms!  Can't use Serverless Application Model for nested stacks :-(
  WrappedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        IntervalMinutes:
          Ref: IntervalMinutes
        NotificationEmail:
          Ref: NotificationEmail
        VoipMSAccount:
          Ref: VoipMSAccount
        VoipMSPassword:
          Ref: VoipMSPassword
        VoipMSUser:
          Ref: VoipMSUser
      TemplateURL: template.yml
Outputs:
  ResultsQueueArn:
    Value:
      Fn::GetAtt: [ResultsQueue, Arn]