AWSTemplateFormatVersion : "2010-09-09"
Description: An experimental test harness for voipms-monitor

Parameters:
  Repo:
    Type: String
  GitHubToken:
    Type: String
    NoEcho: true
  CommitHash:
    Type: String

Resources:
  # Nested stacks cannot contain Transforms!  Can't use Serverless Application Model for nested stacks :-(
  GitHubStatusCustomResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Repo:
          Ref: Repo
        GitHubToken:
          Ref: GitHubToken
        CommitHash:
          Ref: CommitHash
      TemplateURL: githubstatustemplate.yml
  PendingStatus:
    Type: Custom::GitHubStatus
    Properties:
      ServiceToken:
        Fn::GetAtt: [GitHubStatusCustomResourceStack, Outputs.GitHubStatusFunctionArn]
      Repo:
        Ref: Repo
      Context: "continuous-integration/lambci/deploy"
      GitHubToken:
        Ref: GitHubToken
      CommitHash:
        Ref: CommitHash
      State: pending
  # Nested stacks cannot contain Transforms!  Can't use Serverless Application Model for nested stacks :-(
  BadPasswordStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        IntervalMinutes: 2
        NotificationEmail: ""
        VoipMSAccount: "test"
        VoipMSPassword: "test"
        VoipMSUser: "test"
      Tags:
        - Key: Test
          Value: "Bad Password"
      TemplateURL: sqsredirectedtemplate.yml
  CompleteStatus:
    Type: Custom::GitHubStatus
    Properties:
      ServiceToken:
        Fn::GetAtt: [GitHubStatusCustomResourceStack, Outputs.GitHubStatusFunctionArn]
      Repo:
        Ref: Repo
      Context: "continuous-integration/lambci/deploy"
      GitHubToken:
        Ref: GitHubToken
      CommitHash:
        Ref: CommitHash
      State: success
    DependsOn: BadPasswordStack
