AWSTemplateFormatVersion : "2010-09-09"
Description: An experimental test harness for voipms-monitor

Parameters:
  Repo:
    Type: String
  GitHubToken:
    Type: String
    NoEcho: true
  CommitHash:
    Type: String

Resources:
  # Nested stacks cannot contain Transforms!  Can't use Serverless Application Model for nested stacks :-(
  GitHubStatusCustomResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: githubstatustemplate.yml
  PendingStatus:
    Type: Custom::GitHubStatus
    Properties:
      ServiceToken:
        Fn::GetAtt: [GitHubStatusCustomResourceStack, Outputs.GitHubStatusFunctionArn]
      Repo:
        Ref: Repo
      Context: "continuous-integration/functional"
      GitHubToken:
        Ref: GitHubToken
      CommitHash:
        Ref: CommitHash
      Target_URL:
        Fn::Sub:
          https://console.aws.amazon.com/cloudformation/home?region=${AWS::Region}#/stack/detail?stackId=${AWS::StackId}
      Description: "Functional tests starting..."
      State: pending
  # Nested stacks cannot contain Transforms!  Can't use Serverless Application Model for nested stacks :-(
  BadPasswordStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        IntervalMinutes: 2
        NotificationEmail: ""
        VoipMSAccount: "test"
        VoipMSPassword: "test"
        VoipMSUser: "test"
      Tags:
        - Key: Test
          Value: "Bad Password"
      TemplateURL: sqsredirectedtemplate.yml
  CompleteStatus:
    Type: Custom::GitHubStatus
    Properties:
      ServiceToken:
        Fn::GetAtt: [GitHubStatusCustomResourceStack, Outputs.GitHubStatusFunctionArn]
      Repo:
        Ref: Repo
      Context: "continuous-integration/functional"
      GitHubToken:
        Ref: GitHubToken
      CommitHash:
        Ref: CommitHash
      Target_URL:
        Fn::Sub:
          https://console.aws.amazon.com/cloudformation/home?region=${AWS::Region}#/stack/detail?stackId=${AWS::StackId}
      Description: "Functional tests passed!"
      State: success
    DependsOn: BadPasswordStack
